# guard-not-a-hook-entrypoint
# Native git pre-commit hook, not a hooks.json entrypoint. Same shape and same
# reasoning as guard-phantom-staged-deletion-precommit.py: staged-set-for-
# THIS-commit is only directly readable at pre-commit time, and a
# `PreToolUse` hook sees one tool call, never a commit's whole staged diff.
"""Native git pre-commit hook: refuse a commit that removes a hook script
`coordinator/hooks/hooks.json` still registers at HEAD, unless that same
commit also removes the registration.

Closes `state/bug-backlog/2026-07-29-deleting-a-registered-hook-script-is-
an-e9b2e6b3a200.yaml`'s remaining gap: the fail-open bootstrap and the
commit-time parity test (`test_hook_registrations_fail_open.py::
test_every_referenced_hook_script_exists`) already make the outage
survivable and DETECT the drift once it lands -- neither one DENIES the
commit that creates it. This is that denial.

ALL LOGIC LIVES IN `_hook_script_deregistration.py`, which is pure and unit
tested (`coordinator/tests/test_hook_script_deregistration.py`). This file
is the untested wrapper: run git, hand the rows over, print, exit. Do not
move predicate logic in here -- a git hook is not reachable from `pytest`
without spawning, and the suite's spawn budget is already in breach.

NEVER TAKES `.git/index.lock`. Every git call here is a read (`diff --cached`,
`show`) and passes `--no-optional-locks`, same discipline as the phantom-
staged-deletion guard -- a detector that serialises commits on a shared tree
would be worse than the bug it prevents.

INHERITS `GIT_INDEX_FILE` deliberately (see the phantom-staged-deletion
guard's own docstring for the full argument): for a pathspec commit
(`git commit -- <paths>`) git builds a temporary index holding only those
paths, so `git diff --cached` here sees exactly what THIS commit carries,
and `git show :coordinator/hooks/hooks.json` reads that same temporary
index's copy of hooks.json -- absent from it (not an error to alarm on)
exactly when hooks.json is not part of this commit at all.

Fail-open on every git failure and on a missing/malformed HEAD hooks.json --
a defect in this guard's own plumbing must never become a universal commit
block; it degrades to "this guard did not run this commit," same posture as
its sibling native-hook guards.

REGISTRATION. Wired into `.git/hooks/pre-commit`'s gate chain, which is
regenerated by the engine plane's own pre-commit installer (its
`_GATE_REGISTRY`, a cross-repo surface this repo has no standing commit
grant against, DR-127). Same shape as the phantom-staged-deletion guard's
own history: it shipped here first and was registered on the engine
plane's side by a separate cross-repo ask
(`state/memo-outbox/sent/register-phantom-guard-in-gate-registry.md`).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _hook_script_deregistration import (  # noqa: E402
    classify,
    parse_name_status_z,
    render_report,
)

OVERRIDE_ENV = "COORDINATOR_OVERRIDE_HOOK_SCRIPT_DEREGISTRATION"
_HOOKS_JSON_PATH = "coordinator/hooks/hooks.json"


def _git(*args: str) -> "subprocess.CompletedProcess[bytes]":
    return subprocess.run(
        ["git", "--no-optional-locks", *args],
        capture_output=True,
        check=False,
        # A git hook runs on every commit, including from headless Windows
        # shells where a console-spawning child flashes a window each time.
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )


def main() -> int:
    if os.environ.get(OVERRIDE_ENV):
        return 0

    staged = _git("diff", "--cached", "--name-status", "-z", "-M")
    if staged.returncode != 0:
        # An unreadable staged set is not evidence of a violation. Fail OPEN
        # and say so: a pre-commit hook that blocks whenever git hiccups
        # gets uninstalled, and this guard is worth more alive than strict.
        print(
            "[hook-script-deregistration-guard] could not read the staged set "
            f"(git exited {staged.returncode}); allowing the commit",
            file=sys.stderr,
        )
        return 0

    rows = parse_name_status_z(staged.stdout.decode("utf-8", "surrogateescape"))
    if not any(status in ("D", "R") for status, _old, _new in rows):
        return 0

    head_hooks_json = _git("show", f"HEAD:{_HOOKS_JSON_PATH}")
    head_hooks_json_text = (
        head_hooks_json.stdout.decode("utf-8", "surrogateescape")
        if head_hooks_json.returncode == 0
        else None
    )

    hooks_json_touched = any(
        path == _HOOKS_JSON_PATH
        for _status, old, new in rows
        for path in (old, new)
        if path
    )
    staged_hooks_json_text = None
    if hooks_json_touched:
        staged_hooks_json = _git("show", f":{_HOOKS_JSON_PATH}")
        if staged_hooks_json.returncode == 0:
            staged_hooks_json_text = staged_hooks_json.stdout.decode(
                "utf-8", "surrogateescape"
            )
        else:
            # A nonzero exit here USUALLY means hooks.json itself has no
            # staged blob (this commit deletes it outright) --
            # `staged_hooks_json_text` stays None either way, which
            # `classify()` treats as "nothing left registered" (fail-open,
            # never a block). But a nonzero exit can also mean some OTHER
            # git failure (corrupt/unreadable blob) that is not actually a
            # deletion -- distinguish the two so the latter is visible
            # instead of silently degrading into "deletion".
            stderr_text = staged_hooks_json.stderr.decode(
                "utf-8", "surrogateescape"
            )
            if "does not exist" not in stderr_text:
                print(
                    "[hook-script-deregistration-guard] git show of the "
                    f"staged {_HOOKS_JSON_PATH} failed for a reason other "
                    f"than deletion (git exited {staged_hooks_json.returncode}"
                    f"): {stderr_text.strip()}",
                    file=sys.stderr,
                )

    findings = classify(
        rows,
        head_hooks_json_text=head_hooks_json_text,
        hooks_json_touched=hooks_json_touched,
        staged_hooks_json_text=staged_hooks_json_text,
    )
    if not findings:
        return 0

    print(render_report(findings, OVERRIDE_ENV), file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
