@echo off
setlocal
REM Windows launcher for detect-existing-claude-home.py — python-direct (NO bash re-exec).
REM Generated by coordinator/bin/gen-launcher-shim.py — do NOT hand-edit; regenerate.
REM 2026-07-19 Windows de-bash campaign.
REM Contract this artifact carries itself (measured, not doctrine-linked --
REM the doctrine file lives in a sibling repo and is not resolvable from here):
REM   - On bare-name resolution, PowerShell prefers a "detect-existing-claude-home.ps1" sibling of
REM     this file over this "detect-existing-claude-home.cmd" file itself -- if both exist, `detect-existing-claude-home`
REM     typed bare in a pwsh session runs the .ps1, not this .cmd.
REM   - From PowerShell, quote the `--` separator as '--' when invoking this
REM     launcher -- the PowerShell binder eats a bare `--` before this script
REM     ever sees argv, silently dropping it and everything meant to follow it.
REM     Measured against pwsh 7.6.4 -- see coordinator_core/test_bin_launcher_
REM     parity.py::test_argv_fidelity_matrix.
REM
REM Resolves a Python interpreter and runs the co-located entrypoint "detect-existing-claude-home.py"
REM directly. install-substrate.py substitutes __PYTHON_BIN__ with the
REM absolute interpreter path resolved at install time (fast path: skips the
REM `py -3` double-indirection + the Microsoft Store App Execution Alias
REM picker), or with the empty string when no interpreter was resolvable.
REM Falls back to `where python.exe`, then `py -3` -- when the baked value is
REM empty, still the unsubstituted token, OR names a path that is no longer on
REM disk. That last rung is what makes a `~/.claude` synced between a Mac and a
REM Windows box self-healing instead of a permanent rc=3 path-not-found
REM failure: each launcher carries the OTHER platform's
REM interpreter path, and falling back on non-existence is the only repair that
REM is correct on whichever platform is actually running.
REM
REM No `enabledelayedexpansion`: with it on, cmd.exe scans the WHOLE command
REM line -- including whatever %* substitutes in -- for `!...!` tokens before
REM running it, silently mangling any forwarded argument containing a literal
REM `!` (commit messages, JSON payloads, ...). Each interpreter rung below is
REM isolated behind its own `goto` label instead, so `%ERRORLEVEL%` is read
REM outside any parenthesized block (fresh at that point, not frozen at
REM block-parse-time) with no delayed expansion needed.
set "_py=__PYTHON_BIN__"
if "%_py%"=="__PYTHON_BIN__" set "_py="
if not "%_py%"=="" if exist "%_py%" goto :run_baked
set "_py="

for /f "delims=" %%i in ('where python.exe 2^>nul') do (
    echo %%i| findstr /I /C:"\WindowsApps\" >nul
    if errorlevel 1 (
        set "_py=%%i"
        goto :run_baked
    )
)

where py >nul 2>&1
if not errorlevel 1 goto :run_py3

echo [detect-existing-claude-home] ERROR: no Python interpreter found (python.exe / py -3). 1>&2
echo [detect-existing-claude-home] Install Python: https://www.python.org/downloads/windows/ 1>&2
exit /b 127

:run_baked
"%_py%" "%~dp0detect-existing-claude-home.py" %*
exit /b %ERRORLEVEL%

:run_py3
py -3 "%~dp0detect-existing-claude-home.py" %*
exit /b %ERRORLEVEL%
