"""
setup-fnm-pin.py — CLI trampoline over claude-klabauter coordinator_core.ops.setup_fnm_pin.

Repo-setup-time fnm pin resolution: if the target repo has a .node-version or
.nvmrc pin file, installs the pinned Node version via fnm and emits activation
guidance for bare shells. PIN RESOLUTION ONLY — does not install the fnm
binary itself (owned by coordinator:install, a separate chunk). If fnm is
absent, fails loud with actionable remediation.

Invoked as
`"$PYTHON_BIN" "${PYTHON_ARGS[@]}" "${_PLUGIN_ROOT}/lib/setup-fnm-pin.py" "$(pwd)"`
from coordinator/skills/repo-setup/SKILL.md (per `lib/resolve-python.sh`).
Windows parity via the co-located `setup-fnm-pin.cmd` launcher (DR-076),
generated by `coordinator/bin/gen-launcher-shim.py`.

Renamed from `setup-fnm-pin.sh` (a `.sh`-suffixed pure-Python polyglot,
de-polyglotted 28a7b868) to the canonical `.py` suffix — 2026-07-21/22
de-bash campaign (every `.sh` is either ported to Python or renamed when
already Python). The `.sh` suffix's original rationale (avoid a caller path
edit) no longer applies now that every remaining `.sh` is being killed
outright.

Exit convention: fail-loud (gate/config-writer shape, NOT the never-block
auto-push shape) — exits 1 on claude-klabauter-link failure, matching the original
script's own `exit 1` on fnm-absent / repo-root-missing / pin-file-empty.

NOT a capability probe — does not re-implement _co_probe_node from
scripts/lib/prereq_probe.sh. Just fnm binary presence.

Spec backlink: docs/plans/2026-06-23-setup-time-substrate-completeness.md § C1d (AC6)
Port backlink: docs/plans/2026-07-16-bash-clean-slate-residual-migration.md
"""

from __future__ import annotations

import os
import sys

_LIB_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "bin", "lib")
if _LIB_DIR not in sys.path:
    sys.path.insert(0, _LIB_DIR)
from cc_invoke import _resolve_claude_klabauter_root  # noqa: E402


def _import_main():
    claude_klabauter_root = _resolve_claude_klabauter_root()
    if claude_klabauter_root not in sys.path:
        sys.path.insert(0, claude_klabauter_root)
    from coordinator_core.ops.setup_fnm_pin import main as _op_main
    return _op_main


def main() -> None:
    try:
        op_main = _import_main()
    except RuntimeError as exc:
        print(f"setup-fnm-pin.py: CLAUDE_KLABAUTER_ROOT resolution failed: {exc}", file=sys.stderr)
        sys.exit(1)
    except ImportError as exc:
        print(f"setup-fnm-pin.py: coordinator_core.ops.setup_fnm_pin not importable: {exc}", file=sys.stderr)
        sys.exit(1)
    sys.exit(op_main(sys.argv[1:]))


if __name__ == "__main__":
    main()
