#!/usr/bin/env bash
# run-fixture-test.sh — Runs all four phase3d-fixtures and exits non-zero on any mismatch.
#
# spec-backlink: docs/plans/2026-06-14-distill-phase3d-output-budget.md § C4
# test-surface: AC11 (deletion_groups: expansion contract), AC12 (schema_version: 3 fail-loud),
#               AC14 (zero deletions: rows in grouped manifest), AC15 (schema_version: 1 compat)
#
# Fixture layout:
#   fixture-1/  — single-Sonnet-grouped, N=100, 1 cluster (AC11, AC14)
#   fixture-2/  — Workflow-fanout, N=600, 4 clusters (AC11, AC14)
#   fixture-3/  — schema_version: 3 (unsupported), expected abort (AC12)
#   fixture-4/  — schema_version: 1 backward-compat, flat deletions: only (AC15)
#
# DEPENDENCIES: bash >= 4, python3 (PyYAML optional but recommended; pure-stdlib fallback
# not available — the lib script requires PyYAML for robust YAML parsing).
#
# USAGE:
#   bash run-fixture-test.sh           # from any directory
#   bash tests/phase3d-fixtures/run-fixture-test.sh   # from pipeline root
#
# GOLDEN REGENERATION:
#   Review: code-reviewer F12 — document golden regeneration provenance.
#   Goldens were generated by running lib/expand-phase3d-manifest.sh against the fixture
#   inputs and capturing stdout. To regenerate:
#     bash lib/expand-phase3d-manifest.sh fixture-1/input/phase3d-deletion-manifest.md \
#       $(pwd) > fixture-1/golden/expected-delete-set.txt
#     bash lib/expand-phase3d-manifest.sh fixture-2/input/phase3d-deletion-manifest.md \
#       $(pwd) > fixture-2/golden/expected-delete-set.txt
#     bash lib/expand-phase3d-manifest.sh fixture-4/input/phase3d-deletion-manifest.md \
#       fixture-4/input > fixture-4/golden/expected-delete-set.txt
#   Run from the phase3d-fixtures/ directory.

set -euo pipefail

if [ "${BASH_VERSINFO[0]:-0}" -lt 4 ]; then
    echo "ERROR: bash >= 4 required (current: $BASH_VERSION). On macOS: brew install bash." >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
EXPAND="$SCRIPT_DIR/lib/expand-phase3d-manifest.sh"

total_pass=0
total_fail=0
total_skip=0

# ── Helper ───────────────────────────────────────────────────────────────────

run_expansion_fixture() {
    local name="$1"
    local manifest="$2"
    local scout_base="$3"
    local golden="$4"
    local expected_count="$5"

    echo ""
    echo "=== $name ==="

    if [ ! -f "$manifest" ]; then
        echo "FAIL   manifest not found: $manifest"
        total_fail=$((total_fail + 1))
        return
    fi
    if [ ! -f "$golden" ]; then
        echo "FAIL   golden not found: $golden"
        total_fail=$((total_fail + 1))
        return
    fi

    if ! command -v python3 >/dev/null 2>&1; then
        echo "SKIP   python3 not available; cannot exercise expansion"
        return
    fi

    local tmp_out tmp_err
    tmp_out="$(mktemp -t phase3d-fixture-XXXXXX.txt)"
    tmp_err="$(mktemp -t phase3d-fixture-err-XXXXXX.txt)"
    # shellcheck disable=SC2064
    trap "rm -f '$tmp_out' '$tmp_err'" RETURN

    if ! bash "$EXPAND" "$manifest" "$scout_base" > "$tmp_out" 2> "$tmp_err"; then
        echo "FAIL   expand-phase3d-manifest.sh exited non-zero"
        echo "       stderr: $(cat "$tmp_err")"
        total_fail=$((total_fail + 1))
        return
    fi

    # Verify no ERROR lines in stderr (WARNs about non-.md exclusions are acceptable)
    if grep -q "^ERROR:" "$tmp_err" 2>/dev/null; then
        echo "FAIL   unexpected ERROR in stderr: $(cat "$tmp_err")"
        total_fail=$((total_fail + 1))
        return
    fi

    # Count check
    # Review: code-reviewer F7 — awk '{print $1}' is canonical portable form vs tr -d ' '
    local actual_count
    actual_count="$(wc -l < "$tmp_out" | awk '{print $1}')"
    if [ "$actual_count" = "$expected_count" ]; then
        echo "OK     line count = $actual_count (expected $expected_count)"
        # Review: code-reviewer F5 — count check now increments total_pass so pass
        # accounting matches actual assertion count (was only golden-diff that incremented).
        total_pass=$((total_pass + 1))
    else
        echo "FAIL   line count mismatch: got $actual_count, expected $expected_count"
        total_fail=$((total_fail + 1))
        return
    fi

    # Golden diff
    if diff -u "$golden" "$tmp_out" > /dev/null 2>&1; then
        echo "OK     expanded delete set matches golden"
        total_pass=$((total_pass + 1))
    else
        echo "FAIL   expanded delete set differs from golden:"
        diff -u "$golden" "$tmp_out" | head -40 || true
        total_fail=$((total_fail + 1))
    fi
}

# ── AC14 helper — assert deletions: row count == 0 ───────────────────────────
# Review: code-reviewer F4 — extracted into helper so fixture-2 can also assert AC14.
assert_ac14_zero_deletions() {
    local label="$1"
    local manifest="$2"

    if ! command -v python3 >/dev/null 2>&1; then
        echo "SKIP   AC14 ($label): python3 not available"
        return
    fi

    local deletions_count
    deletions_count="$(python3 -c "
import sys, yaml
content = sys.stdin.read()
lines = content.splitlines()
if lines and lines[0].rstrip() == '---':
    close_idx = None
    for i in range(1, len(lines)):
        if lines[i].rstrip() == '---':
            close_idx = i
            break
    content = '\n'.join(lines[1:close_idx]) if close_idx else '\n'.join(lines[1:])
doc = yaml.safe_load(content)
print(len(doc.get('deletions', []) or []))
" < "$manifest" 2>/dev/null || echo "ERROR")"

    if [ "$deletions_count" = "0" ]; then
        echo "OK     AC14 ($label): deletions: row count = 0 (grouped manifest shape confirmed)"
        total_pass=$((total_pass + 1))
    elif [ "$deletions_count" = "ERROR" ]; then
        echo "SKIP   AC14 ($label): python3 YAML parse failed — skipping count assertion"
    else
        echo "FAIL   AC14 ($label): deletions: row count = $deletions_count (expected 0)"
        total_fail=$((total_fail + 1))
    fi
}

# ── Fixture 1: single-Sonnet-grouped, N=100, 1 cluster (AC11 + AC14) ─────────

echo ""
echo "=== fixture-1: single-Sonnet-grouped N=100 (AC11 + AC14) ==="

F1_MANIFEST="$SCRIPT_DIR/fixture-1/input/phase3d-deletion-manifest.md"
F1_GOLDEN="$SCRIPT_DIR/fixture-1/golden/expected-delete-set.txt"

# AC14: assert deletions: row count == 0 in the Phase 3d manifest
assert_ac14_zero_deletions "fixture-1" "$F1_MANIFEST"

# AC11: expansion contract
run_expansion_fixture \
    "fixture-1 expansion (AC11)" \
    "$F1_MANIFEST" \
    "$SCRIPT_DIR" \
    "$F1_GOLDEN" \
    "100"

# ── Fixture 2: Workflow-fanout, N=600, 4 clusters (AC11 + AC14) ───────────────

echo ""
echo "=== fixture-2: Workflow-fanout N=600 (AC11 + AC14) ==="

F2_MANIFEST="$SCRIPT_DIR/fixture-2/input/phase3d-deletion-manifest.md"

# Review: code-reviewer F4 — AC14 also asserted for fixture-2 fanout manifest
assert_ac14_zero_deletions "fixture-2" "$F2_MANIFEST"

run_expansion_fixture \
    "fixture-2 expansion (AC11, fanout N=600)" \
    "$F2_MANIFEST" \
    "$SCRIPT_DIR" \
    "$SCRIPT_DIR/fixture-2/golden/expected-delete-set.txt" \
    "600"

# ── Fixture 3: schema_version: 3 — fail-loud (AC12) ─────────────────────────

echo ""
echo "=== fixture-3: schema_version: 3 fail-loud (AC12) ==="

F3_MANIFEST="$SCRIPT_DIR/fixture-3/input/phase3d-deletion-manifest.md"
F3_GOLDEN_ERR="$SCRIPT_DIR/fixture-3/golden/expected-error.txt"

if [ ! -f "$F3_MANIFEST" ]; then
    echo "FAIL   manifest not found: $F3_MANIFEST"
    total_fail=$((total_fail + 1))
elif [ ! -f "$F3_GOLDEN_ERR" ]; then
    echo "FAIL   expected-error.txt not found: $F3_GOLDEN_ERR"
    total_fail=$((total_fail + 1))
elif ! command -v python3 >/dev/null 2>&1; then
    echo "SKIP   python3 not available"
else
    # Review: code-reviewer F6 — RETURN trap at script scope is a no-op; restructured
    # fixture-3 block into a subshell-safe section using EXIT trap on tmp files instead,
    # with explicit rm -f at end of block. Temp files are now named before the trap
    # so they are always cleaned up even on early exit within this block.
    tmp_out3="$(mktemp -t fixture3-out-XXXXXX.txt)"
    tmp_err3="$(mktemp -t fixture3-err-XXXXXX.txt)"

    exit_code=0
    bash "$EXPAND" "$F3_MANIFEST" "$SCRIPT_DIR/fixture-3/input" > "$tmp_out3" 2> "$tmp_err3" || exit_code=$?

    if [ "$exit_code" -eq 0 ]; then
        echo "FAIL   AC12: expand returned exit 0 for schema_version: 3 (expected non-zero)"
        total_fail=$((total_fail + 1))
    else
        echo "OK     AC12: expand exited $exit_code (non-zero) for schema_version: 3"
        # Verify the error message contains the expected substring
        expected_substr="$(cat "$F3_GOLDEN_ERR" | tr -d '\n')"
        # Review: code-reviewer F13 — grep -qF for fixed-string match (not regex)
        if grep -qF "$expected_substr" "$tmp_err3" 2>/dev/null; then
            echo "OK     AC12: stderr contains expected error substring: '$expected_substr'"
            total_pass=$((total_pass + 1))
        else
            echo "FAIL   AC12: stderr does not contain '$expected_substr'"
            echo "       actual stderr: $(cat "$tmp_err3")"
            total_fail=$((total_fail + 1))
        fi
    fi

    # Review: code-reviewer F6/F14 — explicit rm -f is the only effective cleanup here
    # (RETURN trap at script scope is a no-op; removed the dead trap).
    rm -f "$tmp_out3" "$tmp_err3"
fi

# ── Fixture 4: schema_version: 1 backward-compat (AC15) ─────────────────────

echo ""
echo "=== fixture-4: schema_version: 1 backward-compat (AC15) ==="

F4_SCRIPT="$SCRIPT_DIR/fixture-4-schema-v1-backcompat.sh"
if [ ! -f "$F4_SCRIPT" ]; then
    echo "FAIL   fixture-4-schema-v1-backcompat.sh not found: $F4_SCRIPT"
    total_fail=$((total_fail + 1))
elif ! command -v python3 >/dev/null 2>&1; then
    echo "SKIP   python3 not available"
    total_skip=$((total_skip + 1))
else
    # Review: code-reviewer F11 — handle exit code 2 from fixture-4 as SKIP separately;
    # fixture-4 script uses exit 2 when python3 is absent to distinguish SKIP from PASS/FAIL.
    f4_exit=0
    bash "$F4_SCRIPT" || f4_exit=$?
    if [ "$f4_exit" -eq 0 ]; then
        total_pass=$((total_pass + 1))
    elif [ "$f4_exit" -eq 2 ]; then
        echo "SKIP   fixture-4 reported prerequisite unavailable (exit 2)"
        total_skip=$((total_skip + 1))
    else
        total_fail=$((total_fail + 1))
    fi
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "========================================"
echo "  phase3d-fixtures: $total_pass passed, $total_fail failed, $total_skip skipped"
echo "========================================"

if [ "$total_fail" -eq 0 ]; then
    echo "PASS — all phase3d-fixture assertions green"
    exit 0
else
    echo "FAIL — $total_fail assertion(s) failed — see errors above"
    exit 1
fi
