const fs = require('fs');
const path = require('path');
const os = require('os');

const PLUGINS_ROOT = path.resolve(os.homedir(), '.claude', 'plugins');

// `plugins/cache/` holds machine-local marketplace installs (versioned dirs like
// `cache/<marketplace>/<plugin>/<version>`). These paths are NOT committed state
// — they're regenerated by `claude plugin install` and routinely drift when
// versions roll forward. Tests asserting on committed repo state should skip
// existence checks for cache-rooted paths.
function isCachePath(p) {
  return typeof p === 'string' && (p.includes(`${path.sep}cache${path.sep}`) || p.includes('/cache/'));
}

function fileExists(filePath) {
  try {
    return fs.statSync(filePath).isFile();
  } catch {
    return false;
  }
}

function dirExists(dirPath) {
  try {
    return fs.statSync(dirPath).isDirectory();
  } catch {
    return false;
  }
}

function readJson(filePath) {
  const raw = fs.readFileSync(filePath, 'utf-8');
  try {
    return JSON.parse(raw);
  } catch (e) {
    throw new Error(`Invalid JSON in ${filePath}: ${e.message}`);
  }
}

function listFiles(dir, ext) {
  if (!dirExists(dir)) return [];
  return fs.readdirSync(dir).filter(f => {
    if (ext && !f.endsWith(ext)) return false;
    return fs.statSync(path.join(dir, f)).isFile();
  });
}

function listDirs(dir) {
  if (!dirExists(dir)) return [];
  return fs.readdirSync(dir).filter(f =>
    fs.statSync(path.join(dir, f)).isDirectory()
  );
}

function getDirectoryMarketplaces() {
  const known = readJson(path.join(PLUGINS_ROOT, 'known_marketplaces.json'));
  const result = [];
  for (const [name, entry] of Object.entries(known)) {
    if (entry.source && entry.source.source === 'directory') {
      result.push({ name, ...entry });
    }
  }
  return result;
}

function getInstalledPlugins() {
  return readJson(path.join(PLUGINS_ROOT, 'installed_plugins.json'));
}

// ---------------------------------------------------------------------------
// Sandbox repo helpers (used by hooks-behavior.test.js)
// ---------------------------------------------------------------------------

/**
 * Create a fresh temp directory with a git repo initialized inside it.
 * Returns the absolute path to the repo root.
 * Callers must pair with cleanupTempRepo() in an after() or finally block.
 */
function mkTempRepo() {
  const { execSync } = require('child_process');
  const tmpBase = fs.mkdtempSync(path.join(os.tmpdir(), 'claude-test-'));
  execSync('git -c init.defaultBranch=main init -q', { cwd: tmpBase, stdio: 'pipe' });
  execSync('git config user.email "test@test.example"', { cwd: tmpBase, stdio: 'pipe' });
  execSync('git config user.name "Test"', { cwd: tmpBase, stdio: 'pipe' });
  // Initial commit so HEAD exists
  fs.writeFileSync(path.join(tmpBase, '.gitkeep'), '');
  execSync('git add .gitkeep', { cwd: tmpBase, stdio: 'pipe' });
  execSync('git commit -q -m "init"', { cwd: tmpBase, stdio: 'pipe' });
  return tmpBase;
}

/**
 * Recursively remove a temp repo created by mkTempRepo().
 * Silent on missing path (already cleaned up).
 */
function cleanupTempRepo(repoPath) {
  if (!repoPath) return;
  try {
    fs.rmSync(repoPath, { recursive: true, force: true });
  } catch {
    // best-effort
  }
}

/**
 * Create a temporary directory containing a single executable script named
 * `scriptName` with the given `scriptBody`.
 * Returns the directory path — prepend this to PATH so the script shadows
 * a real binary (e.g. fake `git` that records argv to a file).
 * Callers must pair with cleanupTempRepo() / fs.rmSync() to remove the dir.
 */
function mkPathShim(scriptName, scriptBody) {
  const shimDir = fs.mkdtempSync(path.join(os.tmpdir(), 'claude-shim-'));
  const shimPath = path.join(shimDir, scriptName);
  const content = scriptBody.startsWith('#!') ? scriptBody : `#!/bin/bash\n${scriptBody}`;
  fs.writeFileSync(shimPath, content, { mode: 0o755 });
  return shimDir;
}

module.exports = {
  PLUGINS_ROOT,
  fileExists,
  dirExists,
  readJson,
  listFiles,
  listDirs,
  getDirectoryMarketplaces,
  getInstalledPlugins,
  mkTempRepo,
  cleanupTempRepo,
  mkPathShim,
  isCachePath,
};
